# Generated by Django 4.2.16 on 2024-10-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectimage",
            name="thumbnail",
            field=models.ImageField(
                editable=False, null=True, upload_to="project_images/thumbnails/"
            ),
        ),
    ]
