# Generated by Django 4.2.16 on 2024-10-27 15:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_projectimage_thumbnail"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectimage",
            name="thumbnail",
        ),
        migrations.AlterField(
            model_name="projectimage",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
